#!/usr/bin/env ruby

REPOROOT = `git rev-parse --show-toplevel`.chomp
CLASSPATH = "#{REPOROOT}:#{REPOROOT}/jars/java-cup-11a.jar:#{REPOROOT}/jars/jflex-1.4.3/bin/jflex"

if ARGV.size != 1 then
  puts "USAGE: QC <Q source file>"
  exit 1
end

system "java -cp #{CLASSPATH} QC #{ARGV[0]}"
