
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 17 12:38:15 GMT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 39;
  public static final int STRING_LITERAL = 50;
  public static final int MULT = 37;
  public static final int CHAR = 14;
  public static final int LTEQ = 43;
  public static final int CONCAT = 40;
  public static final int LPAREN = 22;
  public static final int SEMI = 30;
  public static final int INT = 16;
  public static final int MINUS = 36;
  public static final int RDICT = 29;
  public static final int RPAREN = 23;
  public static final int BOOLEAN_LITERAL = 46;
  public static final int NOT = 53;
  public static final int CHARACTER_LITERAL = 51;
  public static final int AND = 34;
  public static final int LT = 42;
  public static final int IN = 5;
  public static final int TDEF = 2;
  public static final int COMMA = 31;
  public static final int DIV = 38;
  public static final int PLUS = 35;
  public static final int MAIN = 21;
  public static final int IF = 6;
  public static final int ID = 49;
  public static final int DOT = 32;
  public static final int EOF = 0;
  public static final int BOOLEAN = 15;
  public static final int RETURN = 11;
  public static final int error = 1;
  public static final int EQEQ = 41;
  public static final int VOID = 4;
  public static final int EQ = 33;
  public static final int LBRACK = 26;
  public static final int COLON = 45;
  public static final int FOREACH = 8;
  public static final int DICT = 20;
  public static final int LBRACE = 24;
  public static final int ELSE = 7;
  public static final int READ = 12;
  public static final int RBRACK = 27;
  public static final int WHILE = 9;
  public static final int LIST = 19;
  public static final int FLOAT = 17;
  public static final int RBRACE = 25;
  public static final int LEN = 52;
  public static final int STRING = 18;
  public static final int DEF = 3;
  public static final int FLOAT_LITERAL = 48;
  public static final int LDICT = 28;
  public static final int PRINT = 13;
  public static final int DO = 10;
  public static final int NOTEQ = 44;
  public static final int INTEGER_LITERAL = 47;
}

